openapi: 3.0.3
info:
  title: Ensembl Resolver API
  description: Resolver API resolves external urls to Ensembl
  contact:
    email: ensembl-webteam@ebi.ac.uk
  version: 0.0.1
servers:
  - url: https://resolver.ensembl.org
paths:
  /id/{stable_id}:
    get:
      summary: Resolve stable ID with optional query params
      description: Resolves to a beta url when a stable id wih optional query params provided
      parameters:
        - name: stable_id
          in: path
          description: Gene stable id used to represent a gene in a genome.
          required: true
          explode: true
          schema:
            type: string
            example: ENSG00000221914.11
        - name: type
          in: query
          description: Defines a type - gene/transcript/variant etc
          required: false
          schema:
            type: string
            enum: [gene, transcript, variant]
            example:
              gene
        - name: app
          in: query
          description: Choose between apps - Genome Browser/ Entity Viewer
          required: false
          schema:
            type: string
            enum: [genome-browser, entity-viewer]
            example:
              genome-browser
        - name: gca
          in: query
          description: GCA assembly accession id of the genome
          required: false
          schema:
            type: string
            example:
              GCA_000001405.29
      responses:
        '200':
          description: OK
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    assembly_name:
                      type: string
                      description: Assembly name
                    accession_id:
                      type: string
                      description: Assembly accession id
                    species_scientific_name:
                      type: string
                      description: Species scientific name
                    taxonomy_id:
                      type: integer
                      description: Taxonomy id
                    resolved_url:
                      type: string
                      description: Resolved url to Ensembl site
        '302':
          description: Redirect to resolved URL
          headers:
            Location:
              schema:
                type: string
          content: {}
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
components:
  responses:
    400:
      description: Bad Request. Missing stable id in the url
      content:
        text/plain:
          schema:
            type: string
            example: "Bad request"
        application/json:
          schema:
            example: '{"status_code": 400, "details": "Bad request"}'
    404:
      description: Requested url not found
      content:
        text/plain:
          schema:
            type: string
            example: "Not found"
        application/json:
          schema:
            example: '{"status_code": 404, "details": "Not found"}'
    500:
      description: Internal server error
      content:
        text/plain:
          schema:
            type: string
            example: 
              Internal server error
        application/json:
          schema:
            example: '{"status_code": 500, "details": "Internal server error"}'
  
